### ISSUE TITLE
missed tags

### ISSUE THREAD

**Issue by grylem** [wschott/apit#2]
Hi
new version has missing tags unlike the old version (AtomicParsley based)
artistid, iTunes genreid, iTunes playlistid and some others.
Maybe you can add missing tags to the new version?
Regards.

**Comment by wschott** [comment]
Hi,
unfortunately tagging has never worked for these fields (artist ID, genre ID, playlist ID) except for content ID. AtomicParsley seemed like it was writing these tags, but it produced erroneous files.
Reading these tags has worked and is still working for my test files. Nevertheless, the order of the output lines while reading these tags has changed. 

Could you test the mutagen based version with an original iTunes file (they include all the IDs)? 

Which other tags are missing?

Kind regards

**Comment by grylem** [comment]
Hi @wschott
Is it possible to extract more information from https://music.apple.com  url? Like Composer, ISRC, UPC? And of course, write it to a file.

Kind Regards.

**Comment by wschott** [comment]
Hi @grylem ,
I couldn't find that metadata when I was looking for it some time ago. There is an API, that can be used to lookup by e.g. ISRC. But the results did not contain ISRCs (or other data you have mentioned).

Kind regards
